//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Affiliate_branch
    {
        [Key]
        public int Affiliate_branch_id { get; set; }
        public int User_id { get; set; }
        public string Store { get; set; }
        public string type { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Utm_source { get; set; }
        public string Utm_source_remarketing { get; set; }
        public Nullable<int> Position { get; set; }
        public string Status { get; set; }
        public string Code { get; set; }
    }
}
