//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Business
    {
        [Key]
        public int Business_id { get; set; }
        public string Loyalty_id { get; set; }
        public int Affiliate_branch_id { get; set; }
        public string User { get; set; }
        public string Pass { get; set; }
        public string Name { get; set; }
        public string Banner { get; set; }
        public string Descriptions { get; set; }
        public int Date_reg { get; set; }
        public int Position { get; set; }
        public string Status { get; set; }
        public string Userweb_id { get; set; }
    }
}
