//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Business_products
    {
        [Key]
        public int Id  { get; set; }
        public int Business_campaign_id { get; set; }
        public int Product_id { get; set; }
        public string Product_code { get; set; }
        public string Product_color_code { get; set; }
        public string Nhomhang { get; set; }
        public string Brand { get; set; }
        public string Tbl_branch_code { get; set; }
        public DateTime Date_start { get; set; }
        public DateTime Date_end { get; set; }
        public int Position { get; set; }
        public string Status { get; set; }
        public string Promotion_description { get; set; }
        public string Note { get; set; }

        public string Display_type { get; set; }
        public string Promotion_type { get; set; }

        public string Highlights { get; set; }
        public string ImageLink { get; set; }
        public DateTime Modified_date { get; set; }
    }
}
