//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class A_Business_campaign
    {
        [Key]
        public int Business_campaign_id { get; set; }
        public int Business_id { get; set; }
       
        public string Discount_code { get; set; }
        public string Use_code { get; set; }
        public string Campaign_code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime Date_start { get; set; }
        public System.DateTime Date_end { get; set; }
        public int Position { get; set; }
        public string Status { get; set; }

    }
}
