//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;

    public partial class B_BusinessProducts
    {
        [Key]
        public long Id { get; set; }
        public int BusinessId { get; set; }
        public int Product_id { get; set; }
        public string Product_code { get; set; }
        public string Product_color_code { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Position { get; set; }
        public string Status { get; set; }
        public string Promotion_description { get; set; }
        public string Note { get; set; }
        public System.DateTime Modified_date { get; set; }
        public string Nhomhang { get; set; }
        public string Brand { get; set; }
        public decimal Price { get; set; }
        public decimal NoInterestPrice { get; set; }
        public  decimal InterestRatePrice { get; set; }
    }
}
