//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;

    public partial class B_Order
    {
        public B_Order()
        {
            this.B_OrderDetail = new HashSet<B_OrderDetail>();
        }
        [Key]
        public long OrderId { get; set; }
        public string UserId { get; set; }
        public string Sex { get; set; }
        public string Name { get; set; }
        public DateTime? Birthday { get; set; }
        public string Address { get; set; }
        public string AddressShipping { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Cmnd { get; set; }
        public string TenCongty { get; set; }
        public string MaNv { get; set; }
   /*     public string Chucvu { get; set; }
        public string Phongban { get; set; }
        public string Hinhthuclaodong { get; set; }*/
        public int OrderTypeId { get; set; }
        public decimal Total { get; set; }
        public decimal Discount { get; set; }
        public string DiscountDetail { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string Note { get; set; }
        public string PaymentType { get; set; }
        public string DiachiHokhau { get; set; }
        public string NoioHientai { get; set; }
        public string Nghenghiep { get; set; }
        /*     public string TenNguoithan { get; set; }
             public string SodtNguoithan { get; set; }
             public string Thoigianlamviec { get; set; }
             public decimal Luongthuclanh { get; set; }
             public decimal Tongthunhap { get; set; }*/
        public string BusinessCode { get; set; }
        public string MaPhieuxuat { get; set; }
        public string Sohoadon { get; set; }
        public string OrderPos { get; set; }
        public int Thoihanvay { get; set; }
        public int Tratruoc { get; set; }
        public decimal Sotientratruoc { get; set; }
        public decimal Sotientragop { get; set; }
        public string Unit { get; set; }
        public string DistictCode { get; set; }

        public virtual ICollection<B_OrderDetail> B_OrderDetail { get; set; }
    }
}
