//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;


    public partial class B_OrderDetail
    {
        [Key]
        public long OrderDetailId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public long ProductId { get; set; }
        public string ProductColorCode { get; set; }
        public string ProductCode { get; set; }
        public decimal Price { get; set; }
        public int Amount { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public string ProductName { get; set; }

        public string ColorName { get; set; }
     
        public decimal Discount { get; set; }
        public string DiscountCode { get; set; }
        public long ParentId { get; set; }
        public string Imei { get; set; }
    
        public virtual B_Order B_Order { get; set; }
    }
    
    
}
