//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;


    public partial class DM_District
    {
        public DM_District()
        {
            this.DM_Ward = new HashSet<DM_Ward>();
         
        }
        [Key]
        public string Code { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public virtual ICollection<DM_Ward> DM_Ward { get; set; }
        public virtual DM_Province DM_Province { get; set; }

    }
}
