//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_Tragop
    {
        [Key]
        public long Id { get; set; }
        public string Unit { get; set; }
        public string Cauhinh { get; set; }
        public decimal PriceTraGopRange { get; set; }
        public float LaisuatTragop { get; set; }
    }
}
