//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_OrderHistory
    {
        [Key]
        public long Id { get; set; }
        public long OrderId { get; set; }
        public string Userid { get; set; }
        public string Action { get; set; }
        public string Note { get; set; }
        public int StatusOrder { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual O_Order O_Order { get; set; }
    }
}
