//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;

    public partial class O_Payment_deferred
    {
        [Key]
        public long Id { get; set; }
        public long OrderId { get; set; }
        public DateTime BirthDay { get; set; }
        public int Old { get; set; }
        public string Job { get; set; }
        public string Noio { get; set; }
        public string HoKhau { get; set; }
        public string Unit { get; set; }
        public int Tratruoc { get; set; }
        public string Cmnd { get; set; }
        public string District { get; set; }
        public int Status { get; set; }
        public string SO_userid { get; set; }
        public string Payment_userId { get; set; }
        public int Lydohuy { get; set; }
        public string SoHopdong { get; set; }
        public int Thoihanvay { get; set; }
        public string Note { get; set; }
        public decimal Sotientratruoc { get; set; }
        public decimal Sotientragop { get; set; }

    }
}
