//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Category
    {
        [Key]
        public long CategoryId { get; set; }
        public Nullable<long> ParentId { get; set; }
        public string IdPath { get; set; }
        public string CategoryName { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeyword { get; set; }
        public string Status { get; set; }
    }
}
