//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Happycare
    {
        [Key]
        public int HappyCareId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public string GHBHCode { get; set; }
        public Nullable<decimal> GHBHPrice { get; set; }
        public string BVTDCode { get; set; }
        public Nullable<decimal> BVTDPrice { get; set; }
        public string Description { get; set; }
        public string Note { get; set; }
    }
}
