//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace WebComment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_SponsorProduct
    {
        [Key]
        public long Id { get; set; }
        public int SponsorId { get; set; }
        public long ProductId { get; set; }
        public System.DateTime Start_date { get; set; }
        public System.DateTime End_date { get; set; }
        public string Status { get; set; }
        public int Position { get; set; }
        public int Orderby { get; set; }
    
       
    }
}
