// <auto-generated />
namespace WebComment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20161205UpdateTableCM_CommentgetStatus : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20161205UpdateTableCM_CommentgetStatus));
        
        string IMigrationMetadata.Id
        {
            get { return "201612050824422_20161205-UpdateTable-CM_Comment-getStatus"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
