// <auto-generated />
namespace WebComment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20161215_UpdateCommentTableLoaiComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20161215_UpdateCommentTableLoaiComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201612150308284_20161215_UpdateCommentTable-LoaiComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
