// <auto-generated />
namespace WebComment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20161201AddTableCM_TrangThai : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20161201AddTableCM_TrangThai));
        
        string IMigrationMetadata.Id
        {
            get { return "201612010751410_20161201-AddTable-CM_TrangThai"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
