// <auto-generated />
namespace WebComment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20161209UpdateTableCM_ReplyComment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20161209UpdateTableCM_ReplyComment));
        
        string IMigrationMetadata.Id
        {
            get { return "201612090910071_20161209-UpdateTable-CM_ReplyComment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
