// <auto-generated />
namespace WebComment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170118_addtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170118_addtable));
        
        string IMigrationMetadata.Id
        {
            get { return "201701180553479_20170118_addtable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
