//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_VnPostVta
    {
        public long Id { get; set; }
        public string CompanyCode { get; set; }
        public string ListStoreCode { get; set; }
    }
}
