//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNet.Identity.EntityFramework;

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SqlDbContext : IdentityDbContext<Qtht_AspNetUsers>
    {
        public SqlDbContext()
            : base("name=SqlDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DM_CommonData> DM_CommonData { get; set; }
        public virtual DbSet<Log> Logs { get; set; }
        public virtual DbSet<M_VnPostVta> M_VnPostVta { get; set; }
        public virtual DbSet<O_Order> O_Order { get; set; }
        public virtual DbSet<O_OrderHistory> O_OrderHistory { get; set; }
        public virtual DbSet<O_OrderType> O_OrderType { get; set; }
        public virtual DbSet<P_Category> P_Category { get; set; }
        public virtual DbSet<P_Happycare> P_Happycare { get; set; }
        public virtual DbSet<P_Product> P_Product { get; set; }
        public virtual DbSet<P_ProductImage> P_ProductImage { get; set; }
        public virtual DbSet<Qtht_ActionActionGroupRefs> Qtht_ActionActionGroupRefs { get; set; }
        public virtual DbSet<Qtht_ActionGroups> Qtht_ActionGroups { get; set; }
        public virtual DbSet<Qtht_ActionRoleRefs> Qtht_ActionRoleRefs { get; set; }
        public virtual DbSet<Qtht_Actions> Qtht_Actions { get; set; }
        public virtual DbSet<Qtht_ActionUserRefs> Qtht_ActionUserRefs { get; set; }
        public virtual DbSet<Qtht_AspNetRoles> Qtht_AspNetRoles { get; set; }
        public virtual DbSet<Qtht_AspNetUserLogins> Qtht_AspNetUserLogins { get; set; }
        public virtual DbSet<Qtht_AspNetUserRoles> Qtht_AspNetUserRoles { get; set; }
        public virtual DbSet<Qtht_AspNetUsers> Qtht_AspNetUsers { get; set; }
        public virtual DbSet<Qtht_Company> Qtht_Company { get; set; }
        public virtual DbSet<Qtht_UserLoginTokens> Qtht_UserLoginTokens { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<O_OrderCondition> O_OrderCondition { get; set; }
        public virtual DbSet<P_ProductColor> P_ProductColor { get; set; }
        public virtual DbSet<Qtht_AspNetUserClaims> Qtht_AspNetUserClaims { get; set; }
        public virtual DbSet<O_OrderDetail> O_OrderDetail { get; set; }
    }
}
