//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_Order
    {
        public O_Order()
        {
            this.O_OrderHistory = new HashSet<O_OrderHistory>();
            this.O_OrderDetail = new HashSet<O_OrderDetail>();
        }
    
        public long OrderId { get; set; }
        public string UserId { get; set; }
        public string Sex { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string StoreCode { get; set; }
        public int OrderTypeId { get; set; }
        public long OrderSoId { get; set; }
        public decimal Total { get; set; }
        public decimal Discount { get; set; }
        public string DiscountDetail { get; set; }
        public int Status { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ConfirmCode { get; set; }
        public string ShippingUserId { get; set; }
    
        public virtual O_Order O_Order1 { get; set; }
        public virtual O_Order O_Order2 { get; set; }
        public virtual ICollection<O_OrderHistory> O_OrderHistory { get; set; }
        public virtual ICollection<O_OrderDetail> O_OrderDetail { get; set; }
    }
}
