//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class O_OrderDetail
    {
        public long OrderDetailId { get; set; }
        public Nullable<long> OrderId { get; set; }
        public long ProductId { get; set; }
        public string ProductColorCode { get; set; }
        public string ProductCode { get; set; }
        public decimal Price { get; set; }
        public int Amount { get; set; }
        public Nullable<bool> IsMain { get; set; }
        public string Combo { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public string DiscountCode { get; set; }
    
        public virtual O_Order O_Order { get; set; }
    }
}
