//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_Product
    {
        public long ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string ProductImage { get; set; }
        public string StatusExsit { get; set; }
        public string ButtonPrice { get; set; }
        public string ButtonBuy { get; set; }
        public string ShowPriceOffline { get; set; }
        public string ShowPriceOnline { get; set; }
        public string Sellonline { get; set; }
        public Nullable<long> CategoryId { get; set; }
        public string IdPath { get; set; }
        public string Slug { get; set; }
        public Nullable<decimal> PriceExpected { get; set; }
        public string VideoId { get; set; }
        public string ProductFeatures { get; set; }
        public string ProductShortDesc { get; set; }
        public string ProductDesc { get; set; }
        public string ProductStandardImage { get; set; }
        public string ProductStandardDesc { get; set; }
        public string SeoTitle { get; set; }
        public string SeoDescription { get; set; }
        public string SeoKeyword { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
