//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Microsoft.AspNet.Identity.EntityFramework;

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qtht_AspNetUsers:IdentityUser
    {
        public Qtht_AspNetUsers()
        {
            this.Qtht_ActionUserRefs = new HashSet<Qtht_ActionUserRefs>();
            this.Qtht_AspNetUserLogins = new HashSet<Qtht_AspNetUserLogins>();
            this.Qtht_AspNetUserRoles = new HashSet<Qtht_AspNetUserRoles>();
            this.Qtht_AspNetUserClaims = new List<Qtht_AspNetUserClaims>();
        }
    
     //   public string Id { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Sex { get; set; }
        public string PersonalId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastLoginDate { get; set; }
        public Nullable<System.DateTime> LastPasswordChangedDate { get; set; }
        public Nullable<System.DateTime> LastLockoutDate { get; set; }
        public int FailedPasswordAttemptCount { get; set; }
        public string Comment { get; set; }
        public bool AllowRecievedNews { get; set; }
    /*    public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string PhoneNumber { get; set; }
        public bool PhoneNumberConfirmed { get; set; }
        public bool TwoFactorEnabled { get; set; }
        public Nullable<System.DateTime> LockoutEndDateUtc { get; set; }
        public bool LockoutEnabled { get; set; }
        public int AccessFailedCount { get; set; }
        public string UserName { get; set; }*/
        public Nullable<System.DateTime> LastUpdateStatusDate { get; set; }
        public string Status { get; set; }
        public string EmailConfirmToken { get; set; }
        public Nullable<System.DateTime> EmailConfirmTokenExpire { get; set; }
        public string PasswordResetToken { get; set; }
        public Nullable<System.DateTime> PasswordResetTokenExpire { get; set; }
        public string EmployeeId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public string Avatar { get; set; }
    
        public virtual ICollection<Qtht_ActionUserRefs> Qtht_ActionUserRefs { get; set; }
        public virtual ICollection<Qtht_AspNetUserLogins> Qtht_AspNetUserLogins { get; set; }
        public virtual ICollection<Qtht_AspNetUserRoles> Qtht_AspNetUserRoles { get; set; }
        public virtual Qtht_Company Qtht_Company { get; set; }
        public virtual ICollection<Qtht_AspNetUserClaims> Qtht_AspNetUserClaims { get; set; }
    }
}
