//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qtht_ActionRoleRefs
    {
        public int Id { get; set; }
        public int ActionId { get; set; }
        public string RoleId { get; set; }
    
        public virtual Qtht_Actions Qtht_Actions { get; set; }
        public virtual Qtht_AspNetRoles Qtht_AspNetRoles { get; set; }
    }
}
