//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qtht_AspNetRoles
    {
        public Qtht_AspNetRoles()
        {
            this.Qtht_ActionRoleRefs = new HashSet<Qtht_ActionRoleRefs>();
            this.Qtht_AspNetRoles1 = new HashSet<Qtht_AspNetRoles>();
            this.Qtht_AspNetUserRoles = new HashSet<Qtht_AspNetUserRoles>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> LastUpdateDate { get; set; }
        public string CreatedBy { get; set; }
        public string LastUpdateBy { get; set; }
        public string Discriminator { get; set; }
        public string ParentId { get; set; }
        public string Code { get; set; }
        public string Type { get; set; }
        public int Priority { get; set; }
        public int Level { get; set; }
    
        public virtual ICollection<Qtht_ActionRoleRefs> Qtht_ActionRoleRefs { get; set; }
        public virtual ICollection<Qtht_AspNetRoles> Qtht_AspNetRoles1 { get; set; }
        public virtual Qtht_AspNetRoles Parent { get; set; }
        public virtual ICollection<Qtht_AspNetUserRoles> Qtht_AspNetUserRoles { get; set; }
    }
}
