//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qtht_Actions
    {
        public Qtht_Actions()
        {
            this.Qtht_ActionActionGroupRefs = new HashSet<Qtht_ActionActionGroupRefs>();
            this.Qtht_ActionRoleRefs = new HashSet<Qtht_ActionRoleRefs>();
            this.Qtht_ActionUserRefs = new HashSet<Qtht_ActionUserRefs>();
        }
    
        public int Id { get; set; }
        public string PublicDomainName { get; set; }
        public string ControllerName { get; set; }
        public string ActionName { get; set; }
        public string ActionDisplayName { get; set; }
        public string AreaName { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime LastUpdatedDate { get; set; }
        public long LastUpdatedBy { get; set; }
        public string CodeName { get; set; }
        public string ListRole { get; set; }
    
        public virtual ICollection<Qtht_ActionActionGroupRefs> Qtht_ActionActionGroupRefs { get; set; }
        public virtual ICollection<Qtht_ActionRoleRefs> Qtht_ActionRoleRefs { get; set; }
        public virtual ICollection<Qtht_ActionUserRefs> Qtht_ActionUserRefs { get; set; }
    }
}
