//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qtht_Company
    {
        public Qtht_Company()
        {
            this.Qtht_AspNetUsers = new HashSet<Qtht_AspNetUsers>();
            this.Qtht_Company1 = new HashSet<Qtht_Company>();
        }
    
        public long Id { get; set; }
        public string CompanyName { get; set; }
        public string CompanyCode { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<long> ParentCompanyId { get; set; }
        public string Note { get; set; }
        public Nullable<int> CompanyLevel { get; set; }
    
        public virtual ICollection<Qtht_AspNetUsers> Qtht_AspNetUsers { get; set; }
        public virtual ICollection<Qtht_Company> Qtht_Company1 { get; set; }
        public virtual Qtht_Company Qtht_Company2 { get; set; }
    }
}
