//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VNPOST.Data.SqlContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qtht_UserLoginTokens
    {
        public long Id { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Domain { get; set; }
        public string Token { get; set; }
    }
}
